### ISSUE TITLE
If one handler errors, the whole chain fails

### ISSUE THREAD

**Issue by fregante** [developit/mitt#15] opened 2017-01-17 04:39 UTC
```js
import mitt from 'mitt'

let emitter = mitt()
emitter.on('foo', e => console.log('1') )
emitter.on('foo', e => {throw new Error('oops')})
emitter.on('foo', e => console.log('2') )
emitter.emit('foo', { a: 'b' });
// log: 1
// Error!
```

https://runkit.com/587db91c9fe155001473453c/587db91c9fe155001473453d

**Comment by svincent** [comment] 2017-01-17 06:20
@bfred-it What's the expected behavior? At first blush it looks like mitt is doing exactly what I'd expect: nothing.

The (uncaught) throw occurs inside a user-defined callback. As such, it's the callback's responsibility to catch and handle whatever errors might occur. Uncaught errors cause the program to terminate early (after logging 1 and before logging 2).

**Comment by bfred-it** [comment] 2017-01-17 06:23
Not in the browser they don't:

```js
document.body.addEventListener('click', e => console.log(1));
document.body.addEventListener('click', e => {throw new Error('oops')})
document.body.addEventListener('click', e => console.log('2') )
document.body.click()
```

<img width="529" alt="screen shot 2017-01-17 at 15 23 03" src="https://cloud.githubusercontent.com/assets/1402241/22009819/61c0926a-dc3a-11e6-9b5e-482416884a7f.png">

**Comment by bfred-it** [comment] 2017-01-17 06:28
It does however match EventEmitter's behavior... https://runkit.com/587da4c1e972330013a27574/587da4c1e972330013a27575

so alas :(

**Comment by svincent** [comment] 2017-01-17 06:46
This is supposition, but I think throws inside a DOM event callback don't abort the script because of how DOM events interact with the JS event loop. I may be mistaken, but I believe for DOM events each event dispatch is a distinct task queued on the event loop. When a throw occurs in the second callback, the current task terminates. At this point the JS event loop continues on to the next event dispatch (log 2). 

Assuming this is all accurate, it *IS* possible to emulate this behavior, but it may be prohibitively complex. Especially given the minimal byte size of mitt and the desire to support IE9+. See this [setImmediate](https://github.com/YuzuJS/setImmediate) shim or [sasa](https://github.com/kriskowal/asap).

Related: https://jakearchibald.com/2015/tasks-microtasks-queues-and-schedules/

**Comment by bfred-it** [comment] 2017-01-17 06:51
The solution doesn't have to be complex, I alternate between these two:

```js
handlers.forEach(fn => {
  try {
    fn();
  } catch (e) {
    console.error(e);
  }
});
```

Or

```js
handlers.forEach(fn => {
  try {
    fn();
  } catch (e) {
    setTimeout(() => {throw e}); // or setImmediate
  }
});
```

**Comment by svincent** [comment] 2017-01-17 07:00
I got myself turned around trying to think of ways to behave exactly like DOM events. If emulation is sufficient (and I can't think of a reason it isn't), then I'm all on board with your try-catch solution. 

I'd tweak it slightly to sniff console support:

```js
handlers.forEach(fn => {
  try {
    fn();
  } catch (e) {
    if (console && typeof console.error == 'function') console.error(e);
  }
});
```

Never know what kind of crazy stuff people are doing with their globals. 😄

**Comment by developit** [comment] 2017-01-17 12:20
Hmm, this is an interesting thought. I don't like that errors can propagate sideways, and agree it's at the very least counter-productive.  That being said, 100% of these solutions break this:

```js
import mitt from 'mitt'

let events = mitt()
events.on('foo', () => { throw Error('foo') })
try {
  events.emit('foo');
} catch (e) {
  // this should probably be invoked!
  // if errors are swallowed, it won't be.
}
```

This might be another "eventemitter and the DOM are strangely out of sync" issue like #6.

**Comment by bfred-it** [comment] 2017-02-05 08:51
Crazy idea: use promises.

```js
return Promises.all(handlers.map(fn => new Promise(r => r(fn()))))
```

The advantage is that you can still let the user catch errors:

```js
import mitt from 'mitt'

let events = mitt()
events.on('foo', () => { throw Error('foo') })
events.emit('foo').catch(e => {/**/});
```

The disadvantage is that Promises don't visibly throw and that the events are always async

**Comment by developit** [comment] 2017-02-25 21:20
I'm going to close this out because it's for sure out of scope for mitt, but I think there's probably a good case here for a plugin maybe?

```
function safetyMitt(all) {
  let { on, off, emit } = mitt(all),
    wrap = fn => fn._safe || (fn._safe = ((a, b) => { try { return fn(a,b) } catch(e) {} }));
  return {
    on: (type, fn) => on(type, wrap(fn)),
    off: (type, fn) => off(type, wrap(fn)),
    emit
  };
}
```

Also - I remembered:  EventEmitter actually does handle errors, but only if there is an `error` handler registered.  I think we'll want to explore that now that we're down to 183 bytes.

**Comment by monochromer** [comment] 2019-03-25 18:19
how about this way?
```javascript
handlers.forEach(fn => {
  try {
    fn();
  } catch (e) {
    this.emit('@mitt/error', {/*info about error and event type*/})
    // or just this.emit('error', {/* ... */})
  }
});

mitt.on('@mitt/error', someErrorHandler);
```

**Closed** 2019-07-30 19:49 UTC
Labels: enhancement
